# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180113_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='order_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
            preserve_default=False,
        ),
    ]
