# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_order_fied'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Логин', 'verbose_name_plural': 'Логины'},
        ),
    ]
