# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20180113_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='login_user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='order_user',
        ),
        migrations.AddField(
            model_name='order',
            name='id_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
