# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180113_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='computer',
            name='price_computer',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Computer', verbose_name='Название компьютера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_order',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='ID Пользователя'),
        ),
    ]
